// Copyright 1998-2017 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

PRAGMA_DISABLE_DEPRECATION_WARNINGS
#ifdef TOWERDEFENSE_Entity_generated_h
#error "Entity.generated.h already included, missing '#pragma once' in Entity.h"
#endif
#define TOWERDEFENSE_Entity_generated_h

#define TowerDefense_Source_TowerDefense_Entity_h_11_RPC_WRAPPERS \
 \
	DECLARE_FUNCTION(execGetEntityName) \
	{ \
		P_FINISH; \
		P_NATIVE_BEGIN; \
		*(FString*)Z_Param__Result=this->GetEntityName(); \
		P_NATIVE_END; \
	} \
 \
	DECLARE_FUNCTION(execGetCurrentHitPoints) \
	{ \
		P_FINISH; \
		P_NATIVE_BEGIN; \
		*(int32*)Z_Param__Result=this->GetCurrentHitPoints(); \
		P_NATIVE_END; \
	} \
 \
	DECLARE_FUNCTION(execGetMaxHitPoints) \
	{ \
		P_FINISH; \
		P_NATIVE_BEGIN; \
		*(int32*)Z_Param__Result=this->GetMaxHitPoints(); \
		P_NATIVE_END; \
	} \
 \
	DECLARE_FUNCTION(execGetAttack) \
	{ \
		P_FINISH; \
		P_NATIVE_BEGIN; \
		*(int32*)Z_Param__Result=this->GetAttack(); \
		P_NATIVE_END; \
	} \
 \
	DECLARE_FUNCTION(execGetArmor) \
	{ \
		P_FINISH; \
		P_NATIVE_BEGIN; \
		*(int32*)Z_Param__Result=this->GetArmor(); \
		P_NATIVE_END; \
	}


#define TowerDefense_Source_TowerDefense_Entity_h_11_RPC_WRAPPERS_NO_PURE_DECLS \
 \
	DECLARE_FUNCTION(execGetEntityName) \
	{ \
		P_FINISH; \
		P_NATIVE_BEGIN; \
		*(FString*)Z_Param__Result=this->GetEntityName(); \
		P_NATIVE_END; \
	} \
 \
	DECLARE_FUNCTION(execGetCurrentHitPoints) \
	{ \
		P_FINISH; \
		P_NATIVE_BEGIN; \
		*(int32*)Z_Param__Result=this->GetCurrentHitPoints(); \
		P_NATIVE_END; \
	} \
 \
	DECLARE_FUNCTION(execGetMaxHitPoints) \
	{ \
		P_FINISH; \
		P_NATIVE_BEGIN; \
		*(int32*)Z_Param__Result=this->GetMaxHitPoints(); \
		P_NATIVE_END; \
	} \
 \
	DECLARE_FUNCTION(execGetAttack) \
	{ \
		P_FINISH; \
		P_NATIVE_BEGIN; \
		*(int32*)Z_Param__Result=this->GetAttack(); \
		P_NATIVE_END; \
	} \
 \
	DECLARE_FUNCTION(execGetArmor) \
	{ \
		P_FINISH; \
		P_NATIVE_BEGIN; \
		*(int32*)Z_Param__Result=this->GetArmor(); \
		P_NATIVE_END; \
	}


#define TowerDefense_Source_TowerDefense_Entity_h_11_INCLASS_NO_PURE_DECLS \
	private: \
	static void StaticRegisterNativesAEntity(); \
	friend TOWERDEFENSE_API class UClass* Z_Construct_UClass_AEntity(); \
	public: \
	DECLARE_CLASS(AEntity, APawn, COMPILED_IN_FLAGS(0), 0, TEXT("/Script/TowerDefense"), NO_API) \
	DECLARE_SERIALIZER(AEntity) \
	/** Indicates whether the class is compiled into the engine */ \
	enum {IsIntrinsic=COMPILED_IN_INTRINSIC};


#define TowerDefense_Source_TowerDefense_Entity_h_11_INCLASS \
	private: \
	static void StaticRegisterNativesAEntity(); \
	friend TOWERDEFENSE_API class UClass* Z_Construct_UClass_AEntity(); \
	public: \
	DECLARE_CLASS(AEntity, APawn, COMPILED_IN_FLAGS(0), 0, TEXT("/Script/TowerDefense"), NO_API) \
	DECLARE_SERIALIZER(AEntity) \
	/** Indicates whether the class is compiled into the engine */ \
	enum {IsIntrinsic=COMPILED_IN_INTRINSIC};


#define TowerDefense_Source_TowerDefense_Entity_h_11_STANDARD_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	NO_API AEntity(const FObjectInitializer& ObjectInitializer); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(AEntity) \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, AEntity); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(AEntity); \
private: \
	/** Private move- and copy-constructors, should never be used */ \
	NO_API AEntity(AEntity&&); \
	NO_API AEntity(const AEntity&); \
public:


#define TowerDefense_Source_TowerDefense_Entity_h_11_ENHANCED_CONSTRUCTORS \
private: \
	/** Private move- and copy-constructors, should never be used */ \
	NO_API AEntity(AEntity&&); \
	NO_API AEntity(const AEntity&); \
public: \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, AEntity); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(AEntity); \
	DEFINE_DEFAULT_CONSTRUCTOR_CALL(AEntity)


#define TowerDefense_Source_TowerDefense_Entity_h_11_PRIVATE_PROPERTY_OFFSET \
	FORCEINLINE static uint32 __PPO__MaxHitPoints() { return STRUCT_OFFSET(AEntity, MaxHitPoints); } \
	FORCEINLINE static uint32 __PPO__Armor() { return STRUCT_OFFSET(AEntity, Armor); } \
	FORCEINLINE static uint32 __PPO__Attack() { return STRUCT_OFFSET(AEntity, Attack); } \
	FORCEINLINE static uint32 __PPO__CurrentHitPoints() { return STRUCT_OFFSET(AEntity, CurrentHitPoints); } \
	FORCEINLINE static uint32 __PPO__EntityName() { return STRUCT_OFFSET(AEntity, EntityName); } \
	FORCEINLINE static uint32 __PPO__VisibleMesh() { return STRUCT_OFFSET(AEntity, VisibleMesh); } \
	FORCEINLINE static uint32 __PPO__CapsuleComponent() { return STRUCT_OFFSET(AEntity, CapsuleComponent); }


#define TowerDefense_Source_TowerDefense_Entity_h_8_PROLOG
#define TowerDefense_Source_TowerDefense_Entity_h_11_GENERATED_BODY_LEGACY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	TowerDefense_Source_TowerDefense_Entity_h_11_PRIVATE_PROPERTY_OFFSET \
	TowerDefense_Source_TowerDefense_Entity_h_11_RPC_WRAPPERS \
	TowerDefense_Source_TowerDefense_Entity_h_11_INCLASS \
	TowerDefense_Source_TowerDefense_Entity_h_11_STANDARD_CONSTRUCTORS \
public: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#define TowerDefense_Source_TowerDefense_Entity_h_11_GENERATED_BODY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	TowerDefense_Source_TowerDefense_Entity_h_11_PRIVATE_PROPERTY_OFFSET \
	TowerDefense_Source_TowerDefense_Entity_h_11_RPC_WRAPPERS_NO_PURE_DECLS \
	TowerDefense_Source_TowerDefense_Entity_h_11_INCLASS_NO_PURE_DECLS \
	TowerDefense_Source_TowerDefense_Entity_h_11_ENHANCED_CONSTRUCTORS \
private: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID TowerDefense_Source_TowerDefense_Entity_h


PRAGMA_ENABLE_DEPRECATION_WARNINGS
