// Copyright 1998-2017 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

PRAGMA_DISABLE_DEPRECATION_WARNINGS
#ifdef TOWERDEFENSE_HeroController_generated_h
#error "HeroController.generated.h already included, missing '#pragma once' in HeroController.h"
#endif
#define TOWERDEFENSE_HeroController_generated_h

#define TowerDefense_Source_TowerDefense_HeroController_h_16_RPC_WRAPPERS
#define TowerDefense_Source_TowerDefense_HeroController_h_16_RPC_WRAPPERS_NO_PURE_DECLS
#define TowerDefense_Source_TowerDefense_HeroController_h_16_INCLASS_NO_PURE_DECLS \
	private: \
	static void StaticRegisterNativesAHeroController(); \
	friend TOWERDEFENSE_API class UClass* Z_Construct_UClass_AHeroController(); \
	public: \
	DECLARE_CLASS(AHeroController, APlayerController, COMPILED_IN_FLAGS(0 | CLASS_Config), 0, TEXT("/Script/TowerDefense"), NO_API) \
	DECLARE_SERIALIZER(AHeroController) \
	/** Indicates whether the class is compiled into the engine */ \
	enum {IsIntrinsic=COMPILED_IN_INTRINSIC};


#define TowerDefense_Source_TowerDefense_HeroController_h_16_INCLASS \
	private: \
	static void StaticRegisterNativesAHeroController(); \
	friend TOWERDEFENSE_API class UClass* Z_Construct_UClass_AHeroController(); \
	public: \
	DECLARE_CLASS(AHeroController, APlayerController, COMPILED_IN_FLAGS(0 | CLASS_Config), 0, TEXT("/Script/TowerDefense"), NO_API) \
	DECLARE_SERIALIZER(AHeroController) \
	/** Indicates whether the class is compiled into the engine */ \
	enum {IsIntrinsic=COMPILED_IN_INTRINSIC};


#define TowerDefense_Source_TowerDefense_HeroController_h_16_STANDARD_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	NO_API AHeroController(const FObjectInitializer& ObjectInitializer); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(AHeroController) \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, AHeroController); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(AHeroController); \
private: \
	/** Private move- and copy-constructors, should never be used */ \
	NO_API AHeroController(AHeroController&&); \
	NO_API AHeroController(const AHeroController&); \
public:


#define TowerDefense_Source_TowerDefense_HeroController_h_16_ENHANCED_CONSTRUCTORS \
private: \
	/** Private move- and copy-constructors, should never be used */ \
	NO_API AHeroController(AHeroController&&); \
	NO_API AHeroController(const AHeroController&); \
public: \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, AHeroController); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(AHeroController); \
	DEFINE_DEFAULT_CONSTRUCTOR_CALL(AHeroController)


#define TowerDefense_Source_TowerDefense_HeroController_h_16_PRIVATE_PROPERTY_OFFSET
#define TowerDefense_Source_TowerDefense_HeroController_h_13_PROLOG
#define TowerDefense_Source_TowerDefense_HeroController_h_16_GENERATED_BODY_LEGACY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	TowerDefense_Source_TowerDefense_HeroController_h_16_PRIVATE_PROPERTY_OFFSET \
	TowerDefense_Source_TowerDefense_HeroController_h_16_RPC_WRAPPERS \
	TowerDefense_Source_TowerDefense_HeroController_h_16_INCLASS \
	TowerDefense_Source_TowerDefense_HeroController_h_16_STANDARD_CONSTRUCTORS \
public: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#define TowerDefense_Source_TowerDefense_HeroController_h_16_GENERATED_BODY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	TowerDefense_Source_TowerDefense_HeroController_h_16_PRIVATE_PROPERTY_OFFSET \
	TowerDefense_Source_TowerDefense_HeroController_h_16_RPC_WRAPPERS_NO_PURE_DECLS \
	TowerDefense_Source_TowerDefense_HeroController_h_16_INCLASS_NO_PURE_DECLS \
	TowerDefense_Source_TowerDefense_HeroController_h_16_ENHANCED_CONSTRUCTORS \
private: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID TowerDefense_Source_TowerDefense_HeroController_h


PRAGMA_ENABLE_DEPRECATION_WARNINGS
