// Copyright 1998-2017 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

PRAGMA_DISABLE_DEPRECATION_WARNINGS
#ifdef TOWERDEFENSE_Hero_generated_h
#error "Hero.generated.h already included, missing '#pragma once' in Hero.h"
#endif
#define TOWERDEFENSE_Hero_generated_h

#define TowerDefense_Source_TowerDefense_Hero_h_15_RPC_WRAPPERS
#define TowerDefense_Source_TowerDefense_Hero_h_15_RPC_WRAPPERS_NO_PURE_DECLS
#define TowerDefense_Source_TowerDefense_Hero_h_15_INCLASS_NO_PURE_DECLS \
	private: \
	static void StaticRegisterNativesAHero(); \
	friend TOWERDEFENSE_API class UClass* Z_Construct_UClass_AHero(); \
	public: \
	DECLARE_CLASS(AHero, AEntity, COMPILED_IN_FLAGS(0), 0, TEXT("/Script/TowerDefense"), NO_API) \
	DECLARE_SERIALIZER(AHero) \
	/** Indicates whether the class is compiled into the engine */ \
	enum {IsIntrinsic=COMPILED_IN_INTRINSIC};


#define TowerDefense_Source_TowerDefense_Hero_h_15_INCLASS \
	private: \
	static void StaticRegisterNativesAHero(); \
	friend TOWERDEFENSE_API class UClass* Z_Construct_UClass_AHero(); \
	public: \
	DECLARE_CLASS(AHero, AEntity, COMPILED_IN_FLAGS(0), 0, TEXT("/Script/TowerDefense"), NO_API) \
	DECLARE_SERIALIZER(AHero) \
	/** Indicates whether the class is compiled into the engine */ \
	enum {IsIntrinsic=COMPILED_IN_INTRINSIC};


#define TowerDefense_Source_TowerDefense_Hero_h_15_STANDARD_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	NO_API AHero(const FObjectInitializer& ObjectInitializer); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(AHero) \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, AHero); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(AHero); \
private: \
	/** Private move- and copy-constructors, should never be used */ \
	NO_API AHero(AHero&&); \
	NO_API AHero(const AHero&); \
public:


#define TowerDefense_Source_TowerDefense_Hero_h_15_ENHANCED_CONSTRUCTORS \
private: \
	/** Private move- and copy-constructors, should never be used */ \
	NO_API AHero(AHero&&); \
	NO_API AHero(const AHero&); \
public: \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, AHero); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(AHero); \
	DEFINE_DEFAULT_CONSTRUCTOR_CALL(AHero)


#define TowerDefense_Source_TowerDefense_Hero_h_15_PRIVATE_PROPERTY_OFFSET \
	FORCEINLINE static uint32 __PPO__SpringArm() { return STRUCT_OFFSET(AHero, SpringArm); } \
	FORCEINLINE static uint32 __PPO__Camera() { return STRUCT_OFFSET(AHero, Camera); } \
	FORCEINLINE static uint32 __PPO__Movement() { return STRUCT_OFFSET(AHero, Movement); }


#define TowerDefense_Source_TowerDefense_Hero_h_12_PROLOG
#define TowerDefense_Source_TowerDefense_Hero_h_15_GENERATED_BODY_LEGACY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	TowerDefense_Source_TowerDefense_Hero_h_15_PRIVATE_PROPERTY_OFFSET \
	TowerDefense_Source_TowerDefense_Hero_h_15_RPC_WRAPPERS \
	TowerDefense_Source_TowerDefense_Hero_h_15_INCLASS \
	TowerDefense_Source_TowerDefense_Hero_h_15_STANDARD_CONSTRUCTORS \
public: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#define TowerDefense_Source_TowerDefense_Hero_h_15_GENERATED_BODY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	TowerDefense_Source_TowerDefense_Hero_h_15_PRIVATE_PROPERTY_OFFSET \
	TowerDefense_Source_TowerDefense_Hero_h_15_RPC_WRAPPERS_NO_PURE_DECLS \
	TowerDefense_Source_TowerDefense_Hero_h_15_INCLASS_NO_PURE_DECLS \
	TowerDefense_Source_TowerDefense_Hero_h_15_ENHANCED_CONSTRUCTORS \
private: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID TowerDefense_Source_TowerDefense_Hero_h


PRAGMA_ENABLE_DEPRECATION_WARNINGS
