// Copyright 1998-2017 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

PRAGMA_DISABLE_DEPRECATION_WARNINGS
#ifdef TOWERDEFENSE_Projectile_generated_h
#error "Projectile.generated.h already included, missing '#pragma once' in Projectile.h"
#endif
#define TOWERDEFENSE_Projectile_generated_h

#define TowerDefense_Source_TowerDefense_Projectile_h_14_RPC_WRAPPERS
#define TowerDefense_Source_TowerDefense_Projectile_h_14_RPC_WRAPPERS_NO_PURE_DECLS
#define TowerDefense_Source_TowerDefense_Projectile_h_14_INCLASS_NO_PURE_DECLS \
	private: \
	static void StaticRegisterNativesAProjectile(); \
	friend TOWERDEFENSE_API class UClass* Z_Construct_UClass_AProjectile(); \
	public: \
	DECLARE_CLASS(AProjectile, AActor, COMPILED_IN_FLAGS(0), 0, TEXT("/Script/TowerDefense"), NO_API) \
	DECLARE_SERIALIZER(AProjectile) \
	/** Indicates whether the class is compiled into the engine */ \
	enum {IsIntrinsic=COMPILED_IN_INTRINSIC};


#define TowerDefense_Source_TowerDefense_Projectile_h_14_INCLASS \
	private: \
	static void StaticRegisterNativesAProjectile(); \
	friend TOWERDEFENSE_API class UClass* Z_Construct_UClass_AProjectile(); \
	public: \
	DECLARE_CLASS(AProjectile, AActor, COMPILED_IN_FLAGS(0), 0, TEXT("/Script/TowerDefense"), NO_API) \
	DECLARE_SERIALIZER(AProjectile) \
	/** Indicates whether the class is compiled into the engine */ \
	enum {IsIntrinsic=COMPILED_IN_INTRINSIC};


#define TowerDefense_Source_TowerDefense_Projectile_h_14_STANDARD_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	NO_API AProjectile(const FObjectInitializer& ObjectInitializer); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(AProjectile) \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, AProjectile); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(AProjectile); \
private: \
	/** Private move- and copy-constructors, should never be used */ \
	NO_API AProjectile(AProjectile&&); \
	NO_API AProjectile(const AProjectile&); \
public:


#define TowerDefense_Source_TowerDefense_Projectile_h_14_ENHANCED_CONSTRUCTORS \
private: \
	/** Private move- and copy-constructors, should never be used */ \
	NO_API AProjectile(AProjectile&&); \
	NO_API AProjectile(const AProjectile&); \
public: \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, AProjectile); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(AProjectile); \
	DEFINE_DEFAULT_CONSTRUCTOR_CALL(AProjectile)


#define TowerDefense_Source_TowerDefense_Projectile_h_14_PRIVATE_PROPERTY_OFFSET \
	FORCEINLINE static uint32 __PPO__VisibleMesh() { return STRUCT_OFFSET(AProjectile, VisibleMesh); } \
	FORCEINLINE static uint32 __PPO__ProjectileMovement() { return STRUCT_OFFSET(AProjectile, ProjectileMovement); }


#define TowerDefense_Source_TowerDefense_Projectile_h_11_PROLOG
#define TowerDefense_Source_TowerDefense_Projectile_h_14_GENERATED_BODY_LEGACY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	TowerDefense_Source_TowerDefense_Projectile_h_14_PRIVATE_PROPERTY_OFFSET \
	TowerDefense_Source_TowerDefense_Projectile_h_14_RPC_WRAPPERS \
	TowerDefense_Source_TowerDefense_Projectile_h_14_INCLASS \
	TowerDefense_Source_TowerDefense_Projectile_h_14_STANDARD_CONSTRUCTORS \
public: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#define TowerDefense_Source_TowerDefense_Projectile_h_14_GENERATED_BODY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	TowerDefense_Source_TowerDefense_Projectile_h_14_PRIVATE_PROPERTY_OFFSET \
	TowerDefense_Source_TowerDefense_Projectile_h_14_RPC_WRAPPERS_NO_PURE_DECLS \
	TowerDefense_Source_TowerDefense_Projectile_h_14_INCLASS_NO_PURE_DECLS \
	TowerDefense_Source_TowerDefense_Projectile_h_14_ENHANCED_CONSTRUCTORS \
private: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID TowerDefense_Source_TowerDefense_Projectile_h


PRAGMA_ENABLE_DEPRECATION_WARNINGS
