// Copyright 1998-2017 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	Boilerplate C++ definitions for a single module.
	This is automatically generated by UnrealHeaderTool.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "GeneratedCppIncludes.h"
#include "TowerDefense.h"
#include "TowerDefense.generated.dep.h"
PRAGMA_DISABLE_OPTIMIZATION
PRAGMA_DISABLE_DEPRECATION_WARNINGS
void EmptyLinkFunctionForGeneratedCode1TowerDefense() {}
FName TOWERDEFENSE_TargetEnemy = FName(TEXT("TargetEnemy"));
	void AEntity::StaticRegisterNativesAEntity()
	{
		FNativeFunctionRegistrar::RegisterFunction(AEntity::StaticClass(), "GetArmor",(Native)&AEntity::execGetArmor);
		FNativeFunctionRegistrar::RegisterFunction(AEntity::StaticClass(), "GetAttack",(Native)&AEntity::execGetAttack);
		FNativeFunctionRegistrar::RegisterFunction(AEntity::StaticClass(), "GetCurrentHitPoints",(Native)&AEntity::execGetCurrentHitPoints);
		FNativeFunctionRegistrar::RegisterFunction(AEntity::StaticClass(), "GetEntityName",(Native)&AEntity::execGetEntityName);
		FNativeFunctionRegistrar::RegisterFunction(AEntity::StaticClass(), "GetMaxHitPoints",(Native)&AEntity::execGetMaxHitPoints);
	}
	IMPLEMENT_CLASS(AEntity, 3826478191);
	void UPawnMovement::StaticRegisterNativesUPawnMovement()
	{
	}
	IMPLEMENT_CLASS(UPawnMovement, 1142566431);
	void AHero::StaticRegisterNativesAHero()
	{
	}
	IMPLEMENT_CLASS(AHero, 3406514144);
	void AHeroController::StaticRegisterNativesAHeroController()
	{
	}
	IMPLEMENT_CLASS(AHeroController, 2629935920);
	void AProjectile::StaticRegisterNativesAProjectile()
	{
	}
	IMPLEMENT_CLASS(AProjectile, 2143776902);
	void AStructure::StaticRegisterNativesAStructure()
	{
	}
	IMPLEMENT_CLASS(AStructure, 3374359461);
static class UEnum* EDmgTypeEnum_StaticEnum()
{
	extern TOWERDEFENSE_API class UPackage* Z_Construct_UPackage__Script_TowerDefense();
	static class UEnum* Singleton = NULL;
	if (!Singleton)
	{
		extern TOWERDEFENSE_API class UEnum* Z_Construct_UEnum_TowerDefense_EDmgTypeEnum();
		Singleton = GetStaticEnum(Z_Construct_UEnum_TowerDefense_EDmgTypeEnum, Z_Construct_UPackage__Script_TowerDefense(), TEXT("EDmgTypeEnum"));
	}
	return Singleton;
}
static FCompiledInDeferEnum Z_CompiledInDeferEnum_UEnum_EDmgTypeEnum(EDmgTypeEnum_StaticEnum, TEXT("/Script/TowerDefense"), TEXT("EDmgTypeEnum"), false, nullptr, nullptr);
	void ATower::TargetEnemy(float DeltaTime, bool isTargeting)
	{
		Tower_eventTargetEnemy_Parms Parms;
		Parms.DeltaTime=DeltaTime;
		Parms.isTargeting=isTargeting ? true : false;
		ProcessEvent(FindFunctionChecked(TOWERDEFENSE_TargetEnemy),&Parms);
	}
	void ATower::StaticRegisterNativesATower()
	{
		FNativeFunctionRegistrar::RegisterFunction(ATower::StaticClass(), "AttackTarget",(Native)&ATower::execAttackTarget);
		FNativeFunctionRegistrar::RegisterFunction(ATower::StaticClass(), "OnOverlapBegin",(Native)&ATower::execOnOverlapBegin);
		FNativeFunctionRegistrar::RegisterFunction(ATower::StaticClass(), "OnOverlapEnd",(Native)&ATower::execOnOverlapEnd);
		FNativeFunctionRegistrar::RegisterFunction(ATower::StaticClass(), "TargetEnemy",(Native)&ATower::execTargetEnemy);
	}
	IMPLEMENT_CLASS(ATower, 1087180987);
	void AWall::StaticRegisterNativesAWall()
	{
	}
	IMPLEMENT_CLASS(AWall, 899533113);
	void ATowerDefenseGameModeBase::StaticRegisterNativesATowerDefenseGameModeBase()
	{
	}
	IMPLEMENT_CLASS(ATowerDefenseGameModeBase, 271686643);
#if USE_COMPILED_IN_NATIVES
// Cross Module References
	ENGINE_API class UClass* Z_Construct_UClass_APawn();
	ENGINE_API class UClass* Z_Construct_UClass_UCapsuleComponent_NoRegister();
	ENGINE_API class UClass* Z_Construct_UClass_UStaticMeshComponent_NoRegister();
	ENGINE_API class UClass* Z_Construct_UClass_UPawnMovementComponent();
	ENGINE_API class UClass* Z_Construct_UClass_UCameraComponent_NoRegister();
	ENGINE_API class UClass* Z_Construct_UClass_USpringArmComponent_NoRegister();
	ENGINE_API class UClass* Z_Construct_UClass_APlayerController();
	UMG_API class UClass* Z_Construct_UClass_UUserWidget_NoRegister();
	ENGINE_API class UClass* Z_Construct_UClass_AActor();
	ENGINE_API class UClass* Z_Construct_UClass_UProjectileMovementComponent_NoRegister();
	ENGINE_API class UClass* Z_Construct_UClass_USceneComponent_NoRegister();
	ENGINE_API class UScriptStruct* Z_Construct_UScriptStruct_FHitResult();
	ENGINE_API class UClass* Z_Construct_UClass_UPrimitiveComponent_NoRegister();
	ENGINE_API class UClass* Z_Construct_UClass_AActor_NoRegister();
	ENGINE_API class UClass* Z_Construct_UClass_AGameModeBase();

	TOWERDEFENSE_API class UFunction* Z_Construct_UFunction_AEntity_GetArmor();
	TOWERDEFENSE_API class UFunction* Z_Construct_UFunction_AEntity_GetAttack();
	TOWERDEFENSE_API class UFunction* Z_Construct_UFunction_AEntity_GetCurrentHitPoints();
	TOWERDEFENSE_API class UFunction* Z_Construct_UFunction_AEntity_GetEntityName();
	TOWERDEFENSE_API class UFunction* Z_Construct_UFunction_AEntity_GetMaxHitPoints();
	TOWERDEFENSE_API class UClass* Z_Construct_UClass_AEntity_NoRegister();
	TOWERDEFENSE_API class UClass* Z_Construct_UClass_AEntity();
	TOWERDEFENSE_API class UClass* Z_Construct_UClass_UPawnMovement_NoRegister();
	TOWERDEFENSE_API class UClass* Z_Construct_UClass_UPawnMovement();
	TOWERDEFENSE_API class UClass* Z_Construct_UClass_AHero_NoRegister();
	TOWERDEFENSE_API class UClass* Z_Construct_UClass_AHero();
	TOWERDEFENSE_API class UClass* Z_Construct_UClass_AHeroController_NoRegister();
	TOWERDEFENSE_API class UClass* Z_Construct_UClass_AHeroController();
	TOWERDEFENSE_API class UClass* Z_Construct_UClass_AProjectile_NoRegister();
	TOWERDEFENSE_API class UClass* Z_Construct_UClass_AProjectile();
	TOWERDEFENSE_API class UClass* Z_Construct_UClass_AStructure_NoRegister();
	TOWERDEFENSE_API class UClass* Z_Construct_UClass_AStructure();
	TOWERDEFENSE_API class UEnum* Z_Construct_UEnum_TowerDefense_EDmgTypeEnum();
	TOWERDEFENSE_API class UFunction* Z_Construct_UFunction_ATower_AttackTarget();
	TOWERDEFENSE_API class UFunction* Z_Construct_UFunction_ATower_OnOverlapBegin();
	TOWERDEFENSE_API class UFunction* Z_Construct_UFunction_ATower_OnOverlapEnd();
	TOWERDEFENSE_API class UFunction* Z_Construct_UFunction_ATower_TargetEnemy();
	TOWERDEFENSE_API class UClass* Z_Construct_UClass_ATower_NoRegister();
	TOWERDEFENSE_API class UClass* Z_Construct_UClass_ATower();
	TOWERDEFENSE_API class UClass* Z_Construct_UClass_AWall_NoRegister();
	TOWERDEFENSE_API class UClass* Z_Construct_UClass_AWall();
	TOWERDEFENSE_API class UClass* Z_Construct_UClass_ATowerDefenseGameModeBase_NoRegister();
	TOWERDEFENSE_API class UClass* Z_Construct_UClass_ATowerDefenseGameModeBase();
	TOWERDEFENSE_API class UPackage* Z_Construct_UPackage__Script_TowerDefense();
	UFunction* Z_Construct_UFunction_AEntity_GetArmor()
	{
		struct Entity_eventGetArmor_Parms
		{
			int32 ReturnValue;
		};
		UObject* Outer=Z_Construct_UClass_AEntity();
		static UFunction* ReturnFunction = NULL;
		if (!ReturnFunction)
		{
			ReturnFunction = new(EC_InternalUseOnlyConstructor, Outer, TEXT("GetArmor"), RF_Public|RF_Transient|RF_MarkAsNative) UFunction(FObjectInitializer(), NULL, 0x04020401, 65535, sizeof(Entity_eventGetArmor_Parms));
			UProperty* NewProp_ReturnValue = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("ReturnValue"), RF_Public|RF_Transient|RF_MarkAsNative) UIntProperty(CPP_PROPERTY_BASE(ReturnValue, Entity_eventGetArmor_Parms), 0x0010000000000580);
			ReturnFunction->Bind();
			ReturnFunction->StaticLink();
#if WITH_METADATA
			UMetaData* MetaData = ReturnFunction->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnFunction, TEXT("Category"), TEXT("Entity Stats"));
			MetaData->SetValue(ReturnFunction, TEXT("ModuleRelativePath"), TEXT("Entity.h"));
#endif
		}
		return ReturnFunction;
	}
	UFunction* Z_Construct_UFunction_AEntity_GetAttack()
	{
		struct Entity_eventGetAttack_Parms
		{
			int32 ReturnValue;
		};
		UObject* Outer=Z_Construct_UClass_AEntity();
		static UFunction* ReturnFunction = NULL;
		if (!ReturnFunction)
		{
			ReturnFunction = new(EC_InternalUseOnlyConstructor, Outer, TEXT("GetAttack"), RF_Public|RF_Transient|RF_MarkAsNative) UFunction(FObjectInitializer(), NULL, 0x04020401, 65535, sizeof(Entity_eventGetAttack_Parms));
			UProperty* NewProp_ReturnValue = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("ReturnValue"), RF_Public|RF_Transient|RF_MarkAsNative) UIntProperty(CPP_PROPERTY_BASE(ReturnValue, Entity_eventGetAttack_Parms), 0x0010000000000580);
			ReturnFunction->Bind();
			ReturnFunction->StaticLink();
#if WITH_METADATA
			UMetaData* MetaData = ReturnFunction->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnFunction, TEXT("Category"), TEXT("Entity Stats"));
			MetaData->SetValue(ReturnFunction, TEXT("ModuleRelativePath"), TEXT("Entity.h"));
#endif
		}
		return ReturnFunction;
	}
	UFunction* Z_Construct_UFunction_AEntity_GetCurrentHitPoints()
	{
		struct Entity_eventGetCurrentHitPoints_Parms
		{
			int32 ReturnValue;
		};
		UObject* Outer=Z_Construct_UClass_AEntity();
		static UFunction* ReturnFunction = NULL;
		if (!ReturnFunction)
		{
			ReturnFunction = new(EC_InternalUseOnlyConstructor, Outer, TEXT("GetCurrentHitPoints"), RF_Public|RF_Transient|RF_MarkAsNative) UFunction(FObjectInitializer(), NULL, 0x04020401, 65535, sizeof(Entity_eventGetCurrentHitPoints_Parms));
			UProperty* NewProp_ReturnValue = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("ReturnValue"), RF_Public|RF_Transient|RF_MarkAsNative) UIntProperty(CPP_PROPERTY_BASE(ReturnValue, Entity_eventGetCurrentHitPoints_Parms), 0x0010000000000580);
			ReturnFunction->Bind();
			ReturnFunction->StaticLink();
#if WITH_METADATA
			UMetaData* MetaData = ReturnFunction->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnFunction, TEXT("Category"), TEXT("Entity Stats"));
			MetaData->SetValue(ReturnFunction, TEXT("ModuleRelativePath"), TEXT("Entity.h"));
#endif
		}
		return ReturnFunction;
	}
	UFunction* Z_Construct_UFunction_AEntity_GetEntityName()
	{
		struct Entity_eventGetEntityName_Parms
		{
			FString ReturnValue;
		};
		UObject* Outer=Z_Construct_UClass_AEntity();
		static UFunction* ReturnFunction = NULL;
		if (!ReturnFunction)
		{
			ReturnFunction = new(EC_InternalUseOnlyConstructor, Outer, TEXT("GetEntityName"), RF_Public|RF_Transient|RF_MarkAsNative) UFunction(FObjectInitializer(), NULL, 0x04020401, 65535, sizeof(Entity_eventGetEntityName_Parms));
			UProperty* NewProp_ReturnValue = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("ReturnValue"), RF_Public|RF_Transient|RF_MarkAsNative) UStrProperty(CPP_PROPERTY_BASE(ReturnValue, Entity_eventGetEntityName_Parms), 0x0010000000000580);
			ReturnFunction->Bind();
			ReturnFunction->StaticLink();
#if WITH_METADATA
			UMetaData* MetaData = ReturnFunction->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnFunction, TEXT("Category"), TEXT("Entity Stats"));
			MetaData->SetValue(ReturnFunction, TEXT("ModuleRelativePath"), TEXT("Entity.h"));
#endif
		}
		return ReturnFunction;
	}
	UFunction* Z_Construct_UFunction_AEntity_GetMaxHitPoints()
	{
		struct Entity_eventGetMaxHitPoints_Parms
		{
			int32 ReturnValue;
		};
		UObject* Outer=Z_Construct_UClass_AEntity();
		static UFunction* ReturnFunction = NULL;
		if (!ReturnFunction)
		{
			ReturnFunction = new(EC_InternalUseOnlyConstructor, Outer, TEXT("GetMaxHitPoints"), RF_Public|RF_Transient|RF_MarkAsNative) UFunction(FObjectInitializer(), NULL, 0x04020401, 65535, sizeof(Entity_eventGetMaxHitPoints_Parms));
			UProperty* NewProp_ReturnValue = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("ReturnValue"), RF_Public|RF_Transient|RF_MarkAsNative) UIntProperty(CPP_PROPERTY_BASE(ReturnValue, Entity_eventGetMaxHitPoints_Parms), 0x0010000000000580);
			ReturnFunction->Bind();
			ReturnFunction->StaticLink();
#if WITH_METADATA
			UMetaData* MetaData = ReturnFunction->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnFunction, TEXT("Category"), TEXT("Entity Stats"));
			MetaData->SetValue(ReturnFunction, TEXT("ModuleRelativePath"), TEXT("Entity.h"));
#endif
		}
		return ReturnFunction;
	}
	UClass* Z_Construct_UClass_AEntity_NoRegister()
	{
		return AEntity::StaticClass();
	}
	UClass* Z_Construct_UClass_AEntity()
	{
		static UClass* OuterClass = NULL;
		if (!OuterClass)
		{
			Z_Construct_UClass_APawn();
			Z_Construct_UPackage__Script_TowerDefense();
			OuterClass = AEntity::StaticClass();
			if (!(OuterClass->ClassFlags & CLASS_Constructed))
			{
				UObjectForceRegistration(OuterClass);
				OuterClass->ClassFlags |= 0x20900080;

				OuterClass->LinkChild(Z_Construct_UFunction_AEntity_GetArmor());
				OuterClass->LinkChild(Z_Construct_UFunction_AEntity_GetAttack());
				OuterClass->LinkChild(Z_Construct_UFunction_AEntity_GetCurrentHitPoints());
				OuterClass->LinkChild(Z_Construct_UFunction_AEntity_GetEntityName());
				OuterClass->LinkChild(Z_Construct_UFunction_AEntity_GetMaxHitPoints());

PRAGMA_DISABLE_DEPRECATION_WARNINGS
				UProperty* NewProp_CapsuleComponent = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("CapsuleComponent"), RF_Public|RF_Transient|RF_MarkAsNative) UObjectProperty(CPP_PROPERTY_BASE(CapsuleComponent, AEntity), 0x0020080000080009, Z_Construct_UClass_UCapsuleComponent_NoRegister());
				UProperty* NewProp_VisibleMesh = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("VisibleMesh"), RF_Public|RF_Transient|RF_MarkAsNative) UObjectProperty(CPP_PROPERTY_BASE(VisibleMesh, AEntity), 0x0020080000080009, Z_Construct_UClass_UStaticMeshComponent_NoRegister());
				UProperty* NewProp_EntityName = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("EntityName"), RF_Public|RF_Transient|RF_MarkAsNative) UStrProperty(CPP_PROPERTY_BASE(EntityName, AEntity), 0x0020080000000001);
				UProperty* NewProp_CurrentHitPoints = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("CurrentHitPoints"), RF_Public|RF_Transient|RF_MarkAsNative) UIntProperty(CPP_PROPERTY_BASE(CurrentHitPoints, AEntity), 0x0020080000000001);
				UProperty* NewProp_Attack = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("Attack"), RF_Public|RF_Transient|RF_MarkAsNative) UIntProperty(CPP_PROPERTY_BASE(Attack, AEntity), 0x0020080000000001);
				UProperty* NewProp_Armor = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("Armor"), RF_Public|RF_Transient|RF_MarkAsNative) UIntProperty(CPP_PROPERTY_BASE(Armor, AEntity), 0x0020080000000001);
				UProperty* NewProp_MaxHitPoints = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("MaxHitPoints"), RF_Public|RF_Transient|RF_MarkAsNative) UIntProperty(CPP_PROPERTY_BASE(MaxHitPoints, AEntity), 0x0020080000000001);
PRAGMA_ENABLE_DEPRECATION_WARNINGS
				OuterClass->AddFunctionToFunctionMapWithOverriddenName(Z_Construct_UFunction_AEntity_GetArmor(), "GetArmor"); // 925375672
				OuterClass->AddFunctionToFunctionMapWithOverriddenName(Z_Construct_UFunction_AEntity_GetAttack(), "GetAttack"); // 679063448
				OuterClass->AddFunctionToFunctionMapWithOverriddenName(Z_Construct_UFunction_AEntity_GetCurrentHitPoints(), "GetCurrentHitPoints"); // 1947580322
				OuterClass->AddFunctionToFunctionMapWithOverriddenName(Z_Construct_UFunction_AEntity_GetEntityName(), "GetEntityName"); // 468846816
				OuterClass->AddFunctionToFunctionMapWithOverriddenName(Z_Construct_UFunction_AEntity_GetMaxHitPoints(), "GetMaxHitPoints"); // 2300761330
				OuterClass->StaticLink();
#if WITH_METADATA
				UMetaData* MetaData = OuterClass->GetOutermost()->GetMetaData();
				MetaData->SetValue(OuterClass, TEXT("HideCategories"), TEXT("Navigation"));
				MetaData->SetValue(OuterClass, TEXT("IncludePath"), TEXT("Entity.h"));
				MetaData->SetValue(OuterClass, TEXT("ModuleRelativePath"), TEXT("Entity.h"));
				MetaData->SetValue(NewProp_CapsuleComponent, TEXT("Category"), TEXT("Entity"));
				MetaData->SetValue(NewProp_CapsuleComponent, TEXT("EditInline"), TEXT("true"));
				MetaData->SetValue(NewProp_CapsuleComponent, TEXT("ModuleRelativePath"), TEXT("Entity.h"));
				MetaData->SetValue(NewProp_VisibleMesh, TEXT("Category"), TEXT("Entity"));
				MetaData->SetValue(NewProp_VisibleMesh, TEXT("EditInline"), TEXT("true"));
				MetaData->SetValue(NewProp_VisibleMesh, TEXT("ModuleRelativePath"), TEXT("Entity.h"));
				MetaData->SetValue(NewProp_EntityName, TEXT("Category"), TEXT("Entity"));
				MetaData->SetValue(NewProp_EntityName, TEXT("ModuleRelativePath"), TEXT("Entity.h"));
				MetaData->SetValue(NewProp_CurrentHitPoints, TEXT("Category"), TEXT("Entity"));
				MetaData->SetValue(NewProp_CurrentHitPoints, TEXT("ModuleRelativePath"), TEXT("Entity.h"));
				MetaData->SetValue(NewProp_Attack, TEXT("Category"), TEXT("Entity"));
				MetaData->SetValue(NewProp_Attack, TEXT("ModuleRelativePath"), TEXT("Entity.h"));
				MetaData->SetValue(NewProp_Armor, TEXT("Category"), TEXT("Entity"));
				MetaData->SetValue(NewProp_Armor, TEXT("ModuleRelativePath"), TEXT("Entity.h"));
				MetaData->SetValue(NewProp_MaxHitPoints, TEXT("Category"), TEXT("Entity"));
				MetaData->SetValue(NewProp_MaxHitPoints, TEXT("ModuleRelativePath"), TEXT("Entity.h"));
#endif
			}
		}
		check(OuterClass->GetClass());
		return OuterClass;
	}
	static FCompiledInDefer Z_CompiledInDefer_UClass_AEntity(Z_Construct_UClass_AEntity, &AEntity::StaticClass, TEXT("AEntity"), false, nullptr, nullptr, nullptr);
	DEFINE_VTABLE_PTR_HELPER_CTOR(AEntity);
	UClass* Z_Construct_UClass_UPawnMovement_NoRegister()
	{
		return UPawnMovement::StaticClass();
	}
	UClass* Z_Construct_UClass_UPawnMovement()
	{
		static UClass* OuterClass = NULL;
		if (!OuterClass)
		{
			Z_Construct_UClass_UPawnMovementComponent();
			Z_Construct_UPackage__Script_TowerDefense();
			OuterClass = UPawnMovement::StaticClass();
			if (!(OuterClass->ClassFlags & CLASS_Constructed))
			{
				UObjectForceRegistration(OuterClass);
				OuterClass->ClassFlags |= 0x20B00084;


				OuterClass->ClassConfigName = FName(TEXT("Engine"));
				OuterClass->StaticLink();
#if WITH_METADATA
				UMetaData* MetaData = OuterClass->GetOutermost()->GetMetaData();
				MetaData->SetValue(OuterClass, TEXT("IncludePath"), TEXT("PawnMovement.h"));
				MetaData->SetValue(OuterClass, TEXT("ModuleRelativePath"), TEXT("PawnMovement.h"));
#endif
			}
		}
		check(OuterClass->GetClass());
		return OuterClass;
	}
	static FCompiledInDefer Z_CompiledInDefer_UClass_UPawnMovement(Z_Construct_UClass_UPawnMovement, &UPawnMovement::StaticClass, TEXT("UPawnMovement"), false, nullptr, nullptr, nullptr);
	DEFINE_VTABLE_PTR_HELPER_CTOR(UPawnMovement);
	UClass* Z_Construct_UClass_AHero_NoRegister()
	{
		return AHero::StaticClass();
	}
	UClass* Z_Construct_UClass_AHero()
	{
		static UClass* OuterClass = NULL;
		if (!OuterClass)
		{
			Z_Construct_UClass_AEntity();
			Z_Construct_UPackage__Script_TowerDefense();
			OuterClass = AHero::StaticClass();
			if (!(OuterClass->ClassFlags & CLASS_Constructed))
			{
				UObjectForceRegistration(OuterClass);
				OuterClass->ClassFlags |= 0x20900080;


PRAGMA_DISABLE_DEPRECATION_WARNINGS
				UProperty* NewProp_Movement = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("Movement"), RF_Public|RF_Transient|RF_MarkAsNative) UObjectProperty(CPP_PROPERTY_BASE(Movement, AHero), 0x0040000000080009, Z_Construct_UClass_UPawnMovement_NoRegister());
				UProperty* NewProp_Camera = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("Camera"), RF_Public|RF_Transient|RF_MarkAsNative) UObjectProperty(CPP_PROPERTY_BASE(Camera, AHero), 0x0040000000080009, Z_Construct_UClass_UCameraComponent_NoRegister());
				UProperty* NewProp_SpringArm = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("SpringArm"), RF_Public|RF_Transient|RF_MarkAsNative) UObjectProperty(CPP_PROPERTY_BASE(SpringArm, AHero), 0x0040000000080009, Z_Construct_UClass_USpringArmComponent_NoRegister());
PRAGMA_ENABLE_DEPRECATION_WARNINGS
				OuterClass->StaticLink();
#if WITH_METADATA
				UMetaData* MetaData = OuterClass->GetOutermost()->GetMetaData();
				MetaData->SetValue(OuterClass, TEXT("HideCategories"), TEXT("Navigation"));
				MetaData->SetValue(OuterClass, TEXT("IncludePath"), TEXT("Hero.h"));
				MetaData->SetValue(OuterClass, TEXT("ModuleRelativePath"), TEXT("Hero.h"));
				MetaData->SetValue(NewProp_Movement, TEXT("Category"), TEXT("Hero"));
				MetaData->SetValue(NewProp_Movement, TEXT("EditInline"), TEXT("true"));
				MetaData->SetValue(NewProp_Movement, TEXT("ModuleRelativePath"), TEXT("Hero.h"));
				MetaData->SetValue(NewProp_Camera, TEXT("Category"), TEXT("Hero"));
				MetaData->SetValue(NewProp_Camera, TEXT("EditInline"), TEXT("true"));
				MetaData->SetValue(NewProp_Camera, TEXT("ModuleRelativePath"), TEXT("Hero.h"));
				MetaData->SetValue(NewProp_SpringArm, TEXT("Category"), TEXT("Hero"));
				MetaData->SetValue(NewProp_SpringArm, TEXT("EditInline"), TEXT("true"));
				MetaData->SetValue(NewProp_SpringArm, TEXT("ModuleRelativePath"), TEXT("Hero.h"));
#endif
			}
		}
		check(OuterClass->GetClass());
		return OuterClass;
	}
	static FCompiledInDefer Z_CompiledInDefer_UClass_AHero(Z_Construct_UClass_AHero, &AHero::StaticClass, TEXT("AHero"), false, nullptr, nullptr, nullptr);
	DEFINE_VTABLE_PTR_HELPER_CTOR(AHero);
	UClass* Z_Construct_UClass_AHeroController_NoRegister()
	{
		return AHeroController::StaticClass();
	}
	UClass* Z_Construct_UClass_AHeroController()
	{
		static UClass* OuterClass = NULL;
		if (!OuterClass)
		{
			Z_Construct_UClass_APlayerController();
			Z_Construct_UPackage__Script_TowerDefense();
			OuterClass = AHeroController::StaticClass();
			if (!(OuterClass->ClassFlags & CLASS_Constructed))
			{
				UObjectForceRegistration(OuterClass);
				OuterClass->ClassFlags |= 0x20900284;


PRAGMA_DISABLE_DEPRECATION_WARNINGS
				UProperty* NewProp_Hero = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("Hero"), RF_Public|RF_Transient|RF_MarkAsNative) UObjectProperty(CPP_PROPERTY_BASE(Hero, AHeroController), 0x0010000000000000, Z_Construct_UClass_AHero_NoRegister());
				UProperty* NewProp_HeroStats = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("HeroStats"), RF_Public|RF_Transient|RF_MarkAsNative) UObjectProperty(CPP_PROPERTY_BASE(HeroStats, AHeroController), 0x0010000000000000, Z_Construct_UClass_UUserWidget_NoRegister());
				UProperty* NewProp_wHeroStats = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("wHeroStats"), RF_Public|RF_Transient|RF_MarkAsNative) UClassProperty(CPP_PROPERTY_BASE(wHeroStats, AHeroController), 0x0014000000000005, Z_Construct_UClass_UUserWidget_NoRegister(), UClass::StaticClass());
PRAGMA_ENABLE_DEPRECATION_WARNINGS
				OuterClass->ClassConfigName = FName(TEXT("Game"));
				OuterClass->StaticLink();
#if WITH_METADATA
				UMetaData* MetaData = OuterClass->GetOutermost()->GetMetaData();
				MetaData->SetValue(OuterClass, TEXT("HideCategories"), TEXT("Collision Rendering Utilities|Transformation"));
				MetaData->SetValue(OuterClass, TEXT("IncludePath"), TEXT("HeroController.h"));
				MetaData->SetValue(OuterClass, TEXT("ModuleRelativePath"), TEXT("HeroController.h"));
				MetaData->SetValue(NewProp_Hero, TEXT("ModuleRelativePath"), TEXT("HeroController.h"));
				MetaData->SetValue(NewProp_HeroStats, TEXT("ModuleRelativePath"), TEXT("HeroController.h"));
				MetaData->SetValue(NewProp_HeroStats, TEXT("ToolTip"), TEXT("Variable to hold the widget After Creating it."));
				MetaData->SetValue(NewProp_wHeroStats, TEXT("Category"), TEXT("Widgets"));
				MetaData->SetValue(NewProp_wHeroStats, TEXT("ModuleRelativePath"), TEXT("HeroController.h"));
				MetaData->SetValue(NewProp_wHeroStats, TEXT("ToolTip"), TEXT("Reference UMG Asset in the Editor"));
#endif
			}
		}
		check(OuterClass->GetClass());
		return OuterClass;
	}
	static FCompiledInDefer Z_CompiledInDefer_UClass_AHeroController(Z_Construct_UClass_AHeroController, &AHeroController::StaticClass, TEXT("AHeroController"), false, nullptr, nullptr, nullptr);
	DEFINE_VTABLE_PTR_HELPER_CTOR(AHeroController);
	UClass* Z_Construct_UClass_AProjectile_NoRegister()
	{
		return AProjectile::StaticClass();
	}
	UClass* Z_Construct_UClass_AProjectile()
	{
		static UClass* OuterClass = NULL;
		if (!OuterClass)
		{
			Z_Construct_UClass_AActor();
			Z_Construct_UPackage__Script_TowerDefense();
			OuterClass = AProjectile::StaticClass();
			if (!(OuterClass->ClassFlags & CLASS_Constructed))
			{
				UObjectForceRegistration(OuterClass);
				OuterClass->ClassFlags |= 0x20900080;


PRAGMA_DISABLE_DEPRECATION_WARNINGS
				UProperty* NewProp_ProjectileMovement = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("ProjectileMovement"), RF_Public|RF_Transient|RF_MarkAsNative) UObjectProperty(CPP_PROPERTY_BASE(ProjectileMovement, AProjectile), 0x0040000000080009, Z_Construct_UClass_UProjectileMovementComponent_NoRegister());
				UProperty* NewProp_VisibleMesh = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("VisibleMesh"), RF_Public|RF_Transient|RF_MarkAsNative) UObjectProperty(CPP_PROPERTY_BASE(VisibleMesh, AProjectile), 0x0040000000080009, Z_Construct_UClass_UStaticMeshComponent_NoRegister());
PRAGMA_ENABLE_DEPRECATION_WARNINGS
				OuterClass->StaticLink();
#if WITH_METADATA
				UMetaData* MetaData = OuterClass->GetOutermost()->GetMetaData();
				MetaData->SetValue(OuterClass, TEXT("IncludePath"), TEXT("Projectile.h"));
				MetaData->SetValue(OuterClass, TEXT("ModuleRelativePath"), TEXT("Projectile.h"));
				MetaData->SetValue(NewProp_ProjectileMovement, TEXT("Category"), TEXT("Projectile"));
				MetaData->SetValue(NewProp_ProjectileMovement, TEXT("EditInline"), TEXT("true"));
				MetaData->SetValue(NewProp_ProjectileMovement, TEXT("ModuleRelativePath"), TEXT("Projectile.h"));
				MetaData->SetValue(NewProp_VisibleMesh, TEXT("Category"), TEXT("Projectile"));
				MetaData->SetValue(NewProp_VisibleMesh, TEXT("EditInline"), TEXT("true"));
				MetaData->SetValue(NewProp_VisibleMesh, TEXT("ModuleRelativePath"), TEXT("Projectile.h"));
#endif
			}
		}
		check(OuterClass->GetClass());
		return OuterClass;
	}
	static FCompiledInDefer Z_CompiledInDefer_UClass_AProjectile(Z_Construct_UClass_AProjectile, &AProjectile::StaticClass, TEXT("AProjectile"), false, nullptr, nullptr, nullptr);
	DEFINE_VTABLE_PTR_HELPER_CTOR(AProjectile);
	UClass* Z_Construct_UClass_AStructure_NoRegister()
	{
		return AStructure::StaticClass();
	}
	UClass* Z_Construct_UClass_AStructure()
	{
		static UClass* OuterClass = NULL;
		if (!OuterClass)
		{
			Z_Construct_UClass_AActor();
			Z_Construct_UPackage__Script_TowerDefense();
			OuterClass = AStructure::StaticClass();
			if (!(OuterClass->ClassFlags & CLASS_Constructed))
			{
				UObjectForceRegistration(OuterClass);
				OuterClass->ClassFlags |= 0x20900080;


PRAGMA_DISABLE_DEPRECATION_WARNINGS
				UProperty* NewProp_VisibleComponent = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("VisibleComponent"), RF_Public|RF_Transient|RF_MarkAsNative) UObjectProperty(CPP_PROPERTY_BASE(VisibleComponent, AStructure), 0x0020080000080009, Z_Construct_UClass_USceneComponent_NoRegister());
PRAGMA_ENABLE_DEPRECATION_WARNINGS
				OuterClass->StaticLink();
#if WITH_METADATA
				UMetaData* MetaData = OuterClass->GetOutermost()->GetMetaData();
				MetaData->SetValue(OuterClass, TEXT("IncludePath"), TEXT("Structure.h"));
				MetaData->SetValue(OuterClass, TEXT("ModuleRelativePath"), TEXT("Structure.h"));
				MetaData->SetValue(NewProp_VisibleComponent, TEXT("Category"), TEXT("Structure"));
				MetaData->SetValue(NewProp_VisibleComponent, TEXT("EditInline"), TEXT("true"));
				MetaData->SetValue(NewProp_VisibleComponent, TEXT("ModuleRelativePath"), TEXT("Structure.h"));
#endif
			}
		}
		check(OuterClass->GetClass());
		return OuterClass;
	}
	static FCompiledInDefer Z_CompiledInDefer_UClass_AStructure(Z_Construct_UClass_AStructure, &AStructure::StaticClass, TEXT("AStructure"), false, nullptr, nullptr, nullptr);
	DEFINE_VTABLE_PTR_HELPER_CTOR(AStructure);
	UEnum* Z_Construct_UEnum_TowerDefense_EDmgTypeEnum()
	{
		UPackage* Outer=Z_Construct_UPackage__Script_TowerDefense();
		extern uint32 Get_Z_Construct_UEnum_TowerDefense_EDmgTypeEnum_CRC();
		static UEnum* ReturnEnum = FindExistingEnumIfHotReloadOrDynamic(Outer, TEXT("EDmgTypeEnum"), 0, Get_Z_Construct_UEnum_TowerDefense_EDmgTypeEnum_CRC(), false);
		if (!ReturnEnum)
		{
			ReturnEnum = new(EC_InternalUseOnlyConstructor, Outer, TEXT("EDmgTypeEnum"), RF_Public|RF_Transient|RF_MarkAsNative) UEnum(FObjectInitializer());
			TArray<TPair<FName, int64>> EnumNames;
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("EDmgTypeEnum::TE_Fire")), 0));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("EDmgTypeEnum::TE_Electic")), 1));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("EDmgTypeEnum::TE_Heavy")), 2));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("EDmgTypeEnum::TE_Normal")), 3));
			EnumNames.Add(TPairInitializer<FName, int64>(FName(TEXT("EDmgTypeEnum::TE_MAX")), 4));
			ReturnEnum->SetEnums(EnumNames, UEnum::ECppForm::EnumClass);
			ReturnEnum->CppType = TEXT("EDmgTypeEnum");
#if WITH_METADATA
			UMetaData* MetaData = ReturnEnum->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnEnum, TEXT("BlueprintType"), TEXT("true"));
			MetaData->SetValue(ReturnEnum, TEXT("ModuleRelativePath"), TEXT("Tower.h"));
			MetaData->SetValue(ReturnEnum, TEXT("TE_Electic.DisplayName"), TEXT("Electic"));
			MetaData->SetValue(ReturnEnum, TEXT("TE_Fire.DisplayName"), TEXT("Fire"));
			MetaData->SetValue(ReturnEnum, TEXT("TE_Heavy.DisplayName"), TEXT("Heavy"));
			MetaData->SetValue(ReturnEnum, TEXT("TE_Normal.DisplayName"), TEXT("Normal"));
#endif
		}
		return ReturnEnum;
	}
	uint32 Get_Z_Construct_UEnum_TowerDefense_EDmgTypeEnum_CRC() { return 2952076677U; }
	UFunction* Z_Construct_UFunction_ATower_AttackTarget()
	{
		UObject* Outer=Z_Construct_UClass_ATower();
		static UFunction* ReturnFunction = NULL;
		if (!ReturnFunction)
		{
			ReturnFunction = new(EC_InternalUseOnlyConstructor, Outer, TEXT("AttackTarget"), RF_Public|RF_Transient|RF_MarkAsNative) UFunction(FObjectInitializer(), NULL, 0x04020401, 65535);
			ReturnFunction->Bind();
			ReturnFunction->StaticLink();
#if WITH_METADATA
			UMetaData* MetaData = ReturnFunction->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnFunction, TEXT("Category"), TEXT("AttackSystem"));
			MetaData->SetValue(ReturnFunction, TEXT("ModuleRelativePath"), TEXT("Tower.h"));
#endif
		}
		return ReturnFunction;
	}
	UFunction* Z_Construct_UFunction_ATower_OnOverlapBegin()
	{
		struct Tower_eventOnOverlapBegin_Parms
		{
			UPrimitiveComponent* OverlappedComp;
			AActor* OtherActor;
			UPrimitiveComponent* OtherComp;
			int32 OtherBodyIndex;
			bool bFromSweep;
			FHitResult SweepResult;
		};
		UObject* Outer=Z_Construct_UClass_ATower();
		static UFunction* ReturnFunction = NULL;
		if (!ReturnFunction)
		{
			ReturnFunction = new(EC_InternalUseOnlyConstructor, Outer, TEXT("OnOverlapBegin"), RF_Public|RF_Transient|RF_MarkAsNative) UFunction(FObjectInitializer(), NULL, 0x00420401, 65535, sizeof(Tower_eventOnOverlapBegin_Parms));
			UProperty* NewProp_SweepResult = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("SweepResult"), RF_Public|RF_Transient|RF_MarkAsNative) UStructProperty(CPP_PROPERTY_BASE(SweepResult, Tower_eventOnOverlapBegin_Parms), 0x0010008008000182, Z_Construct_UScriptStruct_FHitResult());
			CPP_BOOL_PROPERTY_BITMASK_STRUCT(bFromSweep, Tower_eventOnOverlapBegin_Parms, bool);
			UProperty* NewProp_bFromSweep = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("bFromSweep"), RF_Public|RF_Transient|RF_MarkAsNative) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(bFromSweep, Tower_eventOnOverlapBegin_Parms), 0x0010000000000080, CPP_BOOL_PROPERTY_BITMASK(bFromSweep, Tower_eventOnOverlapBegin_Parms), sizeof(bool), true);
			UProperty* NewProp_OtherBodyIndex = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("OtherBodyIndex"), RF_Public|RF_Transient|RF_MarkAsNative) UIntProperty(CPP_PROPERTY_BASE(OtherBodyIndex, Tower_eventOnOverlapBegin_Parms), 0x0010000000000080);
			UProperty* NewProp_OtherComp = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("OtherComp"), RF_Public|RF_Transient|RF_MarkAsNative) UObjectProperty(CPP_PROPERTY_BASE(OtherComp, Tower_eventOnOverlapBegin_Parms), 0x0010000000080080, Z_Construct_UClass_UPrimitiveComponent_NoRegister());
			UProperty* NewProp_OtherActor = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("OtherActor"), RF_Public|RF_Transient|RF_MarkAsNative) UObjectProperty(CPP_PROPERTY_BASE(OtherActor, Tower_eventOnOverlapBegin_Parms), 0x0010000000000080, Z_Construct_UClass_AActor_NoRegister());
			UProperty* NewProp_OverlappedComp = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("OverlappedComp"), RF_Public|RF_Transient|RF_MarkAsNative) UObjectProperty(CPP_PROPERTY_BASE(OverlappedComp, Tower_eventOnOverlapBegin_Parms), 0x0010000000080080, Z_Construct_UClass_UPrimitiveComponent_NoRegister());
			ReturnFunction->Bind();
			ReturnFunction->StaticLink();
#if WITH_METADATA
			UMetaData* MetaData = ReturnFunction->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnFunction, TEXT("ModuleRelativePath"), TEXT("Tower.h"));
			MetaData->SetValue(NewProp_SweepResult, TEXT("NativeConst"), TEXT(""));
			MetaData->SetValue(NewProp_OtherComp, TEXT("EditInline"), TEXT("true"));
			MetaData->SetValue(NewProp_OverlappedComp, TEXT("EditInline"), TEXT("true"));
#endif
		}
		return ReturnFunction;
	}
	UFunction* Z_Construct_UFunction_ATower_OnOverlapEnd()
	{
		struct Tower_eventOnOverlapEnd_Parms
		{
			UPrimitiveComponent* OverlappedComp;
			AActor* OtherActor;
			UPrimitiveComponent* OtherComp;
			int32 OtherBodyIndex;
		};
		UObject* Outer=Z_Construct_UClass_ATower();
		static UFunction* ReturnFunction = NULL;
		if (!ReturnFunction)
		{
			ReturnFunction = new(EC_InternalUseOnlyConstructor, Outer, TEXT("OnOverlapEnd"), RF_Public|RF_Transient|RF_MarkAsNative) UFunction(FObjectInitializer(), NULL, 0x00020401, 65535, sizeof(Tower_eventOnOverlapEnd_Parms));
			UProperty* NewProp_OtherBodyIndex = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("OtherBodyIndex"), RF_Public|RF_Transient|RF_MarkAsNative) UIntProperty(CPP_PROPERTY_BASE(OtherBodyIndex, Tower_eventOnOverlapEnd_Parms), 0x0010000000000080);
			UProperty* NewProp_OtherComp = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("OtherComp"), RF_Public|RF_Transient|RF_MarkAsNative) UObjectProperty(CPP_PROPERTY_BASE(OtherComp, Tower_eventOnOverlapEnd_Parms), 0x0010000000080080, Z_Construct_UClass_UPrimitiveComponent_NoRegister());
			UProperty* NewProp_OtherActor = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("OtherActor"), RF_Public|RF_Transient|RF_MarkAsNative) UObjectProperty(CPP_PROPERTY_BASE(OtherActor, Tower_eventOnOverlapEnd_Parms), 0x0010000000000080, Z_Construct_UClass_AActor_NoRegister());
			UProperty* NewProp_OverlappedComp = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("OverlappedComp"), RF_Public|RF_Transient|RF_MarkAsNative) UObjectProperty(CPP_PROPERTY_BASE(OverlappedComp, Tower_eventOnOverlapEnd_Parms), 0x0010000000080080, Z_Construct_UClass_UPrimitiveComponent_NoRegister());
			ReturnFunction->Bind();
			ReturnFunction->StaticLink();
#if WITH_METADATA
			UMetaData* MetaData = ReturnFunction->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnFunction, TEXT("ModuleRelativePath"), TEXT("Tower.h"));
			MetaData->SetValue(ReturnFunction, TEXT("ToolTip"), TEXT("called when something leaves the sphere component"));
			MetaData->SetValue(NewProp_OtherComp, TEXT("EditInline"), TEXT("true"));
			MetaData->SetValue(NewProp_OverlappedComp, TEXT("EditInline"), TEXT("true"));
#endif
		}
		return ReturnFunction;
	}
	UFunction* Z_Construct_UFunction_ATower_TargetEnemy()
	{
		UObject* Outer=Z_Construct_UClass_ATower();
		static UFunction* ReturnFunction = NULL;
		if (!ReturnFunction)
		{
			ReturnFunction = new(EC_InternalUseOnlyConstructor, Outer, TEXT("TargetEnemy"), RF_Public|RF_Transient|RF_MarkAsNative) UFunction(FObjectInitializer(), NULL, 0x08020C00, 65535, sizeof(Tower_eventTargetEnemy_Parms));
			CPP_BOOL_PROPERTY_BITMASK_STRUCT(isTargeting, Tower_eventTargetEnemy_Parms, bool);
			UProperty* NewProp_isTargeting = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("isTargeting"), RF_Public|RF_Transient|RF_MarkAsNative) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(isTargeting, Tower_eventTargetEnemy_Parms), 0x0010000000000080, CPP_BOOL_PROPERTY_BITMASK(isTargeting, Tower_eventTargetEnemy_Parms), sizeof(bool), true);
			UProperty* NewProp_DeltaTime = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("DeltaTime"), RF_Public|RF_Transient|RF_MarkAsNative) UFloatProperty(CPP_PROPERTY_BASE(DeltaTime, Tower_eventTargetEnemy_Parms), 0x0010000000000080);
			ReturnFunction->Bind();
			ReturnFunction->StaticLink();
#if WITH_METADATA
			UMetaData* MetaData = ReturnFunction->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnFunction, TEXT("Category"), TEXT("AttackSystem"));
			MetaData->SetValue(ReturnFunction, TEXT("ModuleRelativePath"), TEXT("Tower.h"));
#endif
		}
		return ReturnFunction;
	}
	UClass* Z_Construct_UClass_ATower_NoRegister()
	{
		return ATower::StaticClass();
	}
	UClass* Z_Construct_UClass_ATower()
	{
		static UClass* OuterClass = NULL;
		if (!OuterClass)
		{
			Z_Construct_UClass_AStructure();
			Z_Construct_UPackage__Script_TowerDefense();
			OuterClass = ATower::StaticClass();
			if (!(OuterClass->ClassFlags & CLASS_Constructed))
			{
				UObjectForceRegistration(OuterClass);
				OuterClass->ClassFlags |= 0x20900080;

				OuterClass->LinkChild(Z_Construct_UFunction_ATower_AttackTarget());
				OuterClass->LinkChild(Z_Construct_UFunction_ATower_OnOverlapBegin());
				OuterClass->LinkChild(Z_Construct_UFunction_ATower_OnOverlapEnd());
				OuterClass->LinkChild(Z_Construct_UFunction_ATower_TargetEnemy());

PRAGMA_DISABLE_DEPRECATION_WARNINGS
				UProperty* NewProp_AttackSpeed = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("AttackSpeed"), RF_Public|RF_Transient|RF_MarkAsNative) UFloatProperty(CPP_PROPERTY_BASE(AttackSpeed, ATower), 0x0040000000000001);
				UProperty* NewProp_Range = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("Range"), RF_Public|RF_Transient|RF_MarkAsNative) UObjectProperty(CPP_PROPERTY_BASE(Range, ATower), 0x0040000000080009, Z_Construct_UClass_UCapsuleComponent_NoRegister());
				UProperty* NewProp_Turret = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("Turret"), RF_Public|RF_Transient|RF_MarkAsNative) UObjectProperty(CPP_PROPERTY_BASE(Turret, ATower), 0x0040000000080009, Z_Construct_UClass_USceneComponent_NoRegister());
PRAGMA_ENABLE_DEPRECATION_WARNINGS
				OuterClass->AddFunctionToFunctionMapWithOverriddenName(Z_Construct_UFunction_ATower_AttackTarget(), "AttackTarget"); // 2310243392
				OuterClass->AddFunctionToFunctionMapWithOverriddenName(Z_Construct_UFunction_ATower_OnOverlapBegin(), "OnOverlapBegin"); // 1173641261
				OuterClass->AddFunctionToFunctionMapWithOverriddenName(Z_Construct_UFunction_ATower_OnOverlapEnd(), "OnOverlapEnd"); // 3557523921
				OuterClass->AddFunctionToFunctionMapWithOverriddenName(Z_Construct_UFunction_ATower_TargetEnemy(), "TargetEnemy"); // 2932624135
				OuterClass->StaticLink();
#if WITH_METADATA
				UMetaData* MetaData = OuterClass->GetOutermost()->GetMetaData();
				MetaData->SetValue(OuterClass, TEXT("IncludePath"), TEXT("Tower.h"));
				MetaData->SetValue(OuterClass, TEXT("ModuleRelativePath"), TEXT("Tower.h"));
				MetaData->SetValue(NewProp_AttackSpeed, TEXT("Category"), TEXT("Tower"));
				MetaData->SetValue(NewProp_AttackSpeed, TEXT("ModuleRelativePath"), TEXT("Tower.h"));
				MetaData->SetValue(NewProp_Range, TEXT("Category"), TEXT("Tower"));
				MetaData->SetValue(NewProp_Range, TEXT("EditInline"), TEXT("true"));
				MetaData->SetValue(NewProp_Range, TEXT("ModuleRelativePath"), TEXT("Tower.h"));
				MetaData->SetValue(NewProp_Turret, TEXT("Category"), TEXT("Tower"));
				MetaData->SetValue(NewProp_Turret, TEXT("EditInline"), TEXT("true"));
				MetaData->SetValue(NewProp_Turret, TEXT("ModuleRelativePath"), TEXT("Tower.h"));
#endif
			}
		}
		check(OuterClass->GetClass());
		return OuterClass;
	}
	static FCompiledInDefer Z_CompiledInDefer_UClass_ATower(Z_Construct_UClass_ATower, &ATower::StaticClass, TEXT("ATower"), false, nullptr, nullptr, nullptr);
	DEFINE_VTABLE_PTR_HELPER_CTOR(ATower);
	UClass* Z_Construct_UClass_AWall_NoRegister()
	{
		return AWall::StaticClass();
	}
	UClass* Z_Construct_UClass_AWall()
	{
		static UClass* OuterClass = NULL;
		if (!OuterClass)
		{
			Z_Construct_UClass_AStructure();
			Z_Construct_UPackage__Script_TowerDefense();
			OuterClass = AWall::StaticClass();
			if (!(OuterClass->ClassFlags & CLASS_Constructed))
			{
				UObjectForceRegistration(OuterClass);
				OuterClass->ClassFlags |= 0x20900080;


				OuterClass->StaticLink();
#if WITH_METADATA
				UMetaData* MetaData = OuterClass->GetOutermost()->GetMetaData();
				MetaData->SetValue(OuterClass, TEXT("IncludePath"), TEXT("Wall.h"));
				MetaData->SetValue(OuterClass, TEXT("ModuleRelativePath"), TEXT("Wall.h"));
#endif
			}
		}
		check(OuterClass->GetClass());
		return OuterClass;
	}
	static FCompiledInDefer Z_CompiledInDefer_UClass_AWall(Z_Construct_UClass_AWall, &AWall::StaticClass, TEXT("AWall"), false, nullptr, nullptr, nullptr);
	DEFINE_VTABLE_PTR_HELPER_CTOR(AWall);
	UClass* Z_Construct_UClass_ATowerDefenseGameModeBase_NoRegister()
	{
		return ATowerDefenseGameModeBase::StaticClass();
	}
	UClass* Z_Construct_UClass_ATowerDefenseGameModeBase()
	{
		static UClass* OuterClass = NULL;
		if (!OuterClass)
		{
			Z_Construct_UClass_AGameModeBase();
			Z_Construct_UPackage__Script_TowerDefense();
			OuterClass = ATowerDefenseGameModeBase::StaticClass();
			if (!(OuterClass->ClassFlags & CLASS_Constructed))
			{
				UObjectForceRegistration(OuterClass);
				OuterClass->ClassFlags |= 0x20900288;


				OuterClass->StaticLink();
#if WITH_METADATA
				UMetaData* MetaData = OuterClass->GetOutermost()->GetMetaData();
				MetaData->SetValue(OuterClass, TEXT("HideCategories"), TEXT("Info Rendering MovementReplication Replication Actor Input Movement Collision Rendering Utilities|Transformation"));
				MetaData->SetValue(OuterClass, TEXT("IncludePath"), TEXT("TowerDefenseGameModeBase.h"));
				MetaData->SetValue(OuterClass, TEXT("ModuleRelativePath"), TEXT("TowerDefenseGameModeBase.h"));
				MetaData->SetValue(OuterClass, TEXT("ShowCategories"), TEXT("Input|MouseInput Input|TouchInput"));
#endif
			}
		}
		check(OuterClass->GetClass());
		return OuterClass;
	}
	static FCompiledInDefer Z_CompiledInDefer_UClass_ATowerDefenseGameModeBase(Z_Construct_UClass_ATowerDefenseGameModeBase, &ATowerDefenseGameModeBase::StaticClass, TEXT("ATowerDefenseGameModeBase"), false, nullptr, nullptr, nullptr);
	DEFINE_VTABLE_PTR_HELPER_CTOR(ATowerDefenseGameModeBase);
	UPackage* Z_Construct_UPackage__Script_TowerDefense()
	{
		static UPackage* ReturnPackage = NULL;
		if (!ReturnPackage)
		{
			ReturnPackage = CastChecked<UPackage>(StaticFindObjectFast(UPackage::StaticClass(), NULL, FName(TEXT("/Script/TowerDefense")), false, false));
			ReturnPackage->SetPackageFlags(PKG_CompiledIn | 0x00000000);
			FGuid Guid;
			Guid.A = 0x95DC0DB1;
			Guid.B = 0x8F24A0A6;
			Guid.C = 0x00000000;
			Guid.D = 0x00000000;
			ReturnPackage->SetGuid(Guid);

		}
		return ReturnPackage;
	}
#endif

PRAGMA_ENABLE_DEPRECATION_WARNINGS
