// Copyright 1998-2017 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

PRAGMA_DISABLE_DEPRECATION_WARNINGS
#ifdef TOWERDEFENSE_TowerDefenseGameModeBase_generated_h
#error "TowerDefenseGameModeBase.generated.h already included, missing '#pragma once' in TowerDefenseGameModeBase.h"
#endif
#define TOWERDEFENSE_TowerDefenseGameModeBase_generated_h

#define TowerDefense_Source_TowerDefense_TowerDefenseGameModeBase_h_17_RPC_WRAPPERS
#define TowerDefense_Source_TowerDefense_TowerDefenseGameModeBase_h_17_RPC_WRAPPERS_NO_PURE_DECLS
#define TowerDefense_Source_TowerDefense_TowerDefenseGameModeBase_h_17_INCLASS_NO_PURE_DECLS \
	private: \
	static void StaticRegisterNativesATowerDefenseGameModeBase(); \
	friend TOWERDEFENSE_API class UClass* Z_Construct_UClass_ATowerDefenseGameModeBase(); \
	public: \
	DECLARE_CLASS(ATowerDefenseGameModeBase, AGameModeBase, COMPILED_IN_FLAGS(0 | CLASS_Transient), 0, TEXT("/Script/TowerDefense"), NO_API) \
	DECLARE_SERIALIZER(ATowerDefenseGameModeBase) \
	/** Indicates whether the class is compiled into the engine */ \
	enum {IsIntrinsic=COMPILED_IN_INTRINSIC};


#define TowerDefense_Source_TowerDefense_TowerDefenseGameModeBase_h_17_INCLASS \
	private: \
	static void StaticRegisterNativesATowerDefenseGameModeBase(); \
	friend TOWERDEFENSE_API class UClass* Z_Construct_UClass_ATowerDefenseGameModeBase(); \
	public: \
	DECLARE_CLASS(ATowerDefenseGameModeBase, AGameModeBase, COMPILED_IN_FLAGS(0 | CLASS_Transient), 0, TEXT("/Script/TowerDefense"), NO_API) \
	DECLARE_SERIALIZER(ATowerDefenseGameModeBase) \
	/** Indicates whether the class is compiled into the engine */ \
	enum {IsIntrinsic=COMPILED_IN_INTRINSIC};


#define TowerDefense_Source_TowerDefense_TowerDefenseGameModeBase_h_17_STANDARD_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	NO_API ATowerDefenseGameModeBase(const FObjectInitializer& ObjectInitializer); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(ATowerDefenseGameModeBase) \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, ATowerDefenseGameModeBase); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(ATowerDefenseGameModeBase); \
private: \
	/** Private move- and copy-constructors, should never be used */ \
	NO_API ATowerDefenseGameModeBase(ATowerDefenseGameModeBase&&); \
	NO_API ATowerDefenseGameModeBase(const ATowerDefenseGameModeBase&); \
public:


#define TowerDefense_Source_TowerDefense_TowerDefenseGameModeBase_h_17_ENHANCED_CONSTRUCTORS \
private: \
	/** Private move- and copy-constructors, should never be used */ \
	NO_API ATowerDefenseGameModeBase(ATowerDefenseGameModeBase&&); \
	NO_API ATowerDefenseGameModeBase(const ATowerDefenseGameModeBase&); \
public: \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, ATowerDefenseGameModeBase); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(ATowerDefenseGameModeBase); \
	DEFINE_DEFAULT_CONSTRUCTOR_CALL(ATowerDefenseGameModeBase)


#define TowerDefense_Source_TowerDefense_TowerDefenseGameModeBase_h_17_PRIVATE_PROPERTY_OFFSET
#define TowerDefense_Source_TowerDefense_TowerDefenseGameModeBase_h_14_PROLOG
#define TowerDefense_Source_TowerDefense_TowerDefenseGameModeBase_h_17_GENERATED_BODY_LEGACY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	TowerDefense_Source_TowerDefense_TowerDefenseGameModeBase_h_17_PRIVATE_PROPERTY_OFFSET \
	TowerDefense_Source_TowerDefense_TowerDefenseGameModeBase_h_17_RPC_WRAPPERS \
	TowerDefense_Source_TowerDefense_TowerDefenseGameModeBase_h_17_INCLASS \
	TowerDefense_Source_TowerDefense_TowerDefenseGameModeBase_h_17_STANDARD_CONSTRUCTORS \
public: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#define TowerDefense_Source_TowerDefense_TowerDefenseGameModeBase_h_17_GENERATED_BODY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	TowerDefense_Source_TowerDefense_TowerDefenseGameModeBase_h_17_PRIVATE_PROPERTY_OFFSET \
	TowerDefense_Source_TowerDefense_TowerDefenseGameModeBase_h_17_RPC_WRAPPERS_NO_PURE_DECLS \
	TowerDefense_Source_TowerDefense_TowerDefenseGameModeBase_h_17_INCLASS_NO_PURE_DECLS \
	TowerDefense_Source_TowerDefense_TowerDefenseGameModeBase_h_17_ENHANCED_CONSTRUCTORS \
private: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID TowerDefense_Source_TowerDefense_TowerDefenseGameModeBase_h


PRAGMA_ENABLE_DEPRECATION_WARNINGS
