// Copyright 1998-2017 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

PRAGMA_DISABLE_DEPRECATION_WARNINGS
class UPrimitiveComponent;
class AActor;
struct FHitResult;
#ifdef TOWERDEFENSE_Tower_generated_h
#error "Tower.generated.h already included, missing '#pragma once' in Tower.h"
#endif
#define TOWERDEFENSE_Tower_generated_h

#define TowerDefense_Source_TowerDefense_Tower_h_27_RPC_WRAPPERS \
	virtual void TargetEnemy_Implementation(float DeltaTime, bool isTargeting); \
 \
	DECLARE_FUNCTION(execAttackTarget) \
	{ \
		P_FINISH; \
		P_NATIVE_BEGIN; \
		this->AttackTarget(); \
		P_NATIVE_END; \
	} \
 \
	DECLARE_FUNCTION(execTargetEnemy) \
	{ \
		P_GET_PROPERTY(UFloatProperty,Z_Param_DeltaTime); \
		P_GET_UBOOL(Z_Param_isTargeting); \
		P_FINISH; \
		P_NATIVE_BEGIN; \
		this->TargetEnemy_Implementation(Z_Param_DeltaTime,Z_Param_isTargeting); \
		P_NATIVE_END; \
	} \
 \
	DECLARE_FUNCTION(execOnOverlapEnd) \
	{ \
		P_GET_OBJECT(UPrimitiveComponent,Z_Param_OverlappedComp); \
		P_GET_OBJECT(AActor,Z_Param_OtherActor); \
		P_GET_OBJECT(UPrimitiveComponent,Z_Param_OtherComp); \
		P_GET_PROPERTY(UIntProperty,Z_Param_OtherBodyIndex); \
		P_FINISH; \
		P_NATIVE_BEGIN; \
		this->OnOverlapEnd(Z_Param_OverlappedComp,Z_Param_OtherActor,Z_Param_OtherComp,Z_Param_OtherBodyIndex); \
		P_NATIVE_END; \
	} \
 \
	DECLARE_FUNCTION(execOnOverlapBegin) \
	{ \
		P_GET_OBJECT(UPrimitiveComponent,Z_Param_OverlappedComp); \
		P_GET_OBJECT(AActor,Z_Param_OtherActor); \
		P_GET_OBJECT(UPrimitiveComponent,Z_Param_OtherComp); \
		P_GET_PROPERTY(UIntProperty,Z_Param_OtherBodyIndex); \
		P_GET_UBOOL(Z_Param_bFromSweep); \
		P_GET_STRUCT_REF(FHitResult,Z_Param_Out_SweepResult); \
		P_FINISH; \
		P_NATIVE_BEGIN; \
		this->OnOverlapBegin(Z_Param_OverlappedComp,Z_Param_OtherActor,Z_Param_OtherComp,Z_Param_OtherBodyIndex,Z_Param_bFromSweep,Z_Param_Out_SweepResult); \
		P_NATIVE_END; \
	}


#define TowerDefense_Source_TowerDefense_Tower_h_27_RPC_WRAPPERS_NO_PURE_DECLS \
	virtual void TargetEnemy_Implementation(float DeltaTime, bool isTargeting); \
 \
	DECLARE_FUNCTION(execAttackTarget) \
	{ \
		P_FINISH; \
		P_NATIVE_BEGIN; \
		this->AttackTarget(); \
		P_NATIVE_END; \
	} \
 \
	DECLARE_FUNCTION(execTargetEnemy) \
	{ \
		P_GET_PROPERTY(UFloatProperty,Z_Param_DeltaTime); \
		P_GET_UBOOL(Z_Param_isTargeting); \
		P_FINISH; \
		P_NATIVE_BEGIN; \
		this->TargetEnemy_Implementation(Z_Param_DeltaTime,Z_Param_isTargeting); \
		P_NATIVE_END; \
	} \
 \
	DECLARE_FUNCTION(execOnOverlapEnd) \
	{ \
		P_GET_OBJECT(UPrimitiveComponent,Z_Param_OverlappedComp); \
		P_GET_OBJECT(AActor,Z_Param_OtherActor); \
		P_GET_OBJECT(UPrimitiveComponent,Z_Param_OtherComp); \
		P_GET_PROPERTY(UIntProperty,Z_Param_OtherBodyIndex); \
		P_FINISH; \
		P_NATIVE_BEGIN; \
		this->OnOverlapEnd(Z_Param_OverlappedComp,Z_Param_OtherActor,Z_Param_OtherComp,Z_Param_OtherBodyIndex); \
		P_NATIVE_END; \
	} \
 \
	DECLARE_FUNCTION(execOnOverlapBegin) \
	{ \
		P_GET_OBJECT(UPrimitiveComponent,Z_Param_OverlappedComp); \
		P_GET_OBJECT(AActor,Z_Param_OtherActor); \
		P_GET_OBJECT(UPrimitiveComponent,Z_Param_OtherComp); \
		P_GET_PROPERTY(UIntProperty,Z_Param_OtherBodyIndex); \
		P_GET_UBOOL(Z_Param_bFromSweep); \
		P_GET_STRUCT_REF(FHitResult,Z_Param_Out_SweepResult); \
		P_FINISH; \
		P_NATIVE_BEGIN; \
		this->OnOverlapBegin(Z_Param_OverlappedComp,Z_Param_OtherActor,Z_Param_OtherComp,Z_Param_OtherBodyIndex,Z_Param_bFromSweep,Z_Param_Out_SweepResult); \
		P_NATIVE_END; \
	}


#define TowerDefense_Source_TowerDefense_Tower_h_27_EVENT_PARMS \
	struct Tower_eventTargetEnemy_Parms \
	{ \
		float DeltaTime; \
		bool isTargeting; \
	};


extern TOWERDEFENSE_API  FName TOWERDEFENSE_TargetEnemy;
#define TowerDefense_Source_TowerDefense_Tower_h_27_CALLBACK_WRAPPERS
#define TowerDefense_Source_TowerDefense_Tower_h_27_INCLASS_NO_PURE_DECLS \
	private: \
	static void StaticRegisterNativesATower(); \
	friend TOWERDEFENSE_API class UClass* Z_Construct_UClass_ATower(); \
	public: \
	DECLARE_CLASS(ATower, AStructure, COMPILED_IN_FLAGS(0), 0, TEXT("/Script/TowerDefense"), NO_API) \
	DECLARE_SERIALIZER(ATower) \
	/** Indicates whether the class is compiled into the engine */ \
	enum {IsIntrinsic=COMPILED_IN_INTRINSIC};


#define TowerDefense_Source_TowerDefense_Tower_h_27_INCLASS \
	private: \
	static void StaticRegisterNativesATower(); \
	friend TOWERDEFENSE_API class UClass* Z_Construct_UClass_ATower(); \
	public: \
	DECLARE_CLASS(ATower, AStructure, COMPILED_IN_FLAGS(0), 0, TEXT("/Script/TowerDefense"), NO_API) \
	DECLARE_SERIALIZER(ATower) \
	/** Indicates whether the class is compiled into the engine */ \
	enum {IsIntrinsic=COMPILED_IN_INTRINSIC};


#define TowerDefense_Source_TowerDefense_Tower_h_27_STANDARD_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	NO_API ATower(const FObjectInitializer& ObjectInitializer); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(ATower) \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, ATower); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(ATower); \
private: \
	/** Private move- and copy-constructors, should never be used */ \
	NO_API ATower(ATower&&); \
	NO_API ATower(const ATower&); \
public:


#define TowerDefense_Source_TowerDefense_Tower_h_27_ENHANCED_CONSTRUCTORS \
private: \
	/** Private move- and copy-constructors, should never be used */ \
	NO_API ATower(ATower&&); \
	NO_API ATower(const ATower&); \
public: \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, ATower); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(ATower); \
	DEFINE_DEFAULT_CONSTRUCTOR_CALL(ATower)


#define TowerDefense_Source_TowerDefense_Tower_h_27_PRIVATE_PROPERTY_OFFSET \
	FORCEINLINE static uint32 __PPO__Turret() { return STRUCT_OFFSET(ATower, Turret); } \
	FORCEINLINE static uint32 __PPO__Range() { return STRUCT_OFFSET(ATower, Range); } \
	FORCEINLINE static uint32 __PPO__AttackSpeed() { return STRUCT_OFFSET(ATower, AttackSpeed); }


#define TowerDefense_Source_TowerDefense_Tower_h_24_PROLOG \
	TowerDefense_Source_TowerDefense_Tower_h_27_EVENT_PARMS


#define TowerDefense_Source_TowerDefense_Tower_h_27_GENERATED_BODY_LEGACY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	TowerDefense_Source_TowerDefense_Tower_h_27_PRIVATE_PROPERTY_OFFSET \
	TowerDefense_Source_TowerDefense_Tower_h_27_RPC_WRAPPERS \
	TowerDefense_Source_TowerDefense_Tower_h_27_CALLBACK_WRAPPERS \
	TowerDefense_Source_TowerDefense_Tower_h_27_INCLASS \
	TowerDefense_Source_TowerDefense_Tower_h_27_STANDARD_CONSTRUCTORS \
public: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#define TowerDefense_Source_TowerDefense_Tower_h_27_GENERATED_BODY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	TowerDefense_Source_TowerDefense_Tower_h_27_PRIVATE_PROPERTY_OFFSET \
	TowerDefense_Source_TowerDefense_Tower_h_27_RPC_WRAPPERS_NO_PURE_DECLS \
	TowerDefense_Source_TowerDefense_Tower_h_27_CALLBACK_WRAPPERS \
	TowerDefense_Source_TowerDefense_Tower_h_27_INCLASS_NO_PURE_DECLS \
	TowerDefense_Source_TowerDefense_Tower_h_27_ENHANCED_CONSTRUCTORS \
private: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID TowerDefense_Source_TowerDefense_Tower_h


#define FOREACH_ENUM_EDMGTYPEENUM(op) \
	op(EDmgTypeEnum::TE_Fire) \
	op(EDmgTypeEnum::TE_Electic) \
	op(EDmgTypeEnum::TE_Heavy) \
	op(EDmgTypeEnum::TE_Normal) 
PRAGMA_ENABLE_DEPRECATION_WARNINGS
