// Copyright 1998-2017 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

PRAGMA_DISABLE_DEPRECATION_WARNINGS
#ifdef TOWERDEFENSE_Wall_generated_h
#error "Wall.generated.h already included, missing '#pragma once' in Wall.h"
#endif
#define TOWERDEFENSE_Wall_generated_h

#define TowerDefense_Source_TowerDefense_Wall_h_14_RPC_WRAPPERS
#define TowerDefense_Source_TowerDefense_Wall_h_14_RPC_WRAPPERS_NO_PURE_DECLS
#define TowerDefense_Source_TowerDefense_Wall_h_14_INCLASS_NO_PURE_DECLS \
	private: \
	static void StaticRegisterNativesAWall(); \
	friend TOWERDEFENSE_API class UClass* Z_Construct_UClass_AWall(); \
	public: \
	DECLARE_CLASS(AWall, AStructure, COMPILED_IN_FLAGS(0), 0, TEXT("/Script/TowerDefense"), NO_API) \
	DECLARE_SERIALIZER(AWall) \
	/** Indicates whether the class is compiled into the engine */ \
	enum {IsIntrinsic=COMPILED_IN_INTRINSIC};


#define TowerDefense_Source_TowerDefense_Wall_h_14_INCLASS \
	private: \
	static void StaticRegisterNativesAWall(); \
	friend TOWERDEFENSE_API class UClass* Z_Construct_UClass_AWall(); \
	public: \
	DECLARE_CLASS(AWall, AStructure, COMPILED_IN_FLAGS(0), 0, TEXT("/Script/TowerDefense"), NO_API) \
	DECLARE_SERIALIZER(AWall) \
	/** Indicates whether the class is compiled into the engine */ \
	enum {IsIntrinsic=COMPILED_IN_INTRINSIC};


#define TowerDefense_Source_TowerDefense_Wall_h_14_STANDARD_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	NO_API AWall(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(AWall) \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, AWall); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(AWall); \
private: \
	/** Private move- and copy-constructors, should never be used */ \
	NO_API AWall(AWall&&); \
	NO_API AWall(const AWall&); \
public:


#define TowerDefense_Source_TowerDefense_Wall_h_14_ENHANCED_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	NO_API AWall() { }; \
private: \
	/** Private move- and copy-constructors, should never be used */ \
	NO_API AWall(AWall&&); \
	NO_API AWall(const AWall&); \
public: \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, AWall); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(AWall); \
	DEFINE_DEFAULT_CONSTRUCTOR_CALL(AWall)


#define TowerDefense_Source_TowerDefense_Wall_h_14_PRIVATE_PROPERTY_OFFSET
#define TowerDefense_Source_TowerDefense_Wall_h_11_PROLOG
#define TowerDefense_Source_TowerDefense_Wall_h_14_GENERATED_BODY_LEGACY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	TowerDefense_Source_TowerDefense_Wall_h_14_PRIVATE_PROPERTY_OFFSET \
	TowerDefense_Source_TowerDefense_Wall_h_14_RPC_WRAPPERS \
	TowerDefense_Source_TowerDefense_Wall_h_14_INCLASS \
	TowerDefense_Source_TowerDefense_Wall_h_14_STANDARD_CONSTRUCTORS \
public: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#define TowerDefense_Source_TowerDefense_Wall_h_14_GENERATED_BODY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	TowerDefense_Source_TowerDefense_Wall_h_14_PRIVATE_PROPERTY_OFFSET \
	TowerDefense_Source_TowerDefense_Wall_h_14_RPC_WRAPPERS_NO_PURE_DECLS \
	TowerDefense_Source_TowerDefense_Wall_h_14_INCLASS_NO_PURE_DECLS \
	TowerDefense_Source_TowerDefense_Wall_h_14_ENHANCED_CONSTRUCTORS \
private: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID TowerDefense_Source_TowerDefense_Wall_h


PRAGMA_ENABLE_DEPRECATION_WARNINGS
